name: polkabot

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  contents: read

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: us-central1
  REPO_NAME: polkabot

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set environment variable
        run: |
          echo "REPO_NAME=polkabot" >> $GITHUB_ENV

      - name: Build and tag the docker image
        run: |
          touch .env.local
          echo NEXT_PUBLIC_OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }} >> .env.local
          echo NEXT_PUBLIC_PINECONE_API_KEY=${{ secrets.NEXT_PUBLIC_PINECONE_API_KEY }} >> .env.local
          echo NEXT_PUBLIC_PINECONE_ENVIRONMENT=${{ secrets.NEXT_PUBLIC_PINECONE_ENVIRONMENT }} >> .env.local
          docker build . --tag us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/steno:$GITHUB_SHA

      - name: Push the image to the Google Container Registry
        run: |-
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/steno:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --execution-environment gen2 \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/steno:$GITHUB_SHA \
          --platform "managed" \
          --quiet
